### ISSUE TITLE
Thoughts on binding 1 listener to the document and handling events internally?

### ISSUE THREAD

**Issue by phated** [maxogden/yo-yo#17]
I'm not sure if it is more efficient or maybe it adds too much to the library (could be split out into another module), but my understanding is that React binds a single `addEventListener` to the document and matches events to elements in the tree.  I think this is for performance reasons (I've heard about this in other libraries too).  Do you think it makes sense to have some implementation of this in yo-yo instead of attaching handlers directly to the elements?

**Comment by shama** [comment]
Oh that's an interesting idea. We should explore that.

**Comment by SilentCicero** [comment]
@shama we could just check event.target with onclick or event bindings. That would be awesome, and so simple.

**Comment by shama** [comment]
After exploring it a little, a concern I have is it would likely require something top level to manage it. Which if implemented into `yo-yo` would mean peer dependencies as we couldn't have multiple top level event managers.

I'm curious about the performance difference between one top level event manager vs many event handlers on elements though. I wonder if it would be possible to build a library that could capture the native `addEventListener` calls so a user could choose to apply the optimization at their app level and avoid peer dependencies.

**Comment by SilentCicero** [comment]
@shama you can just use a simple caching system like I use in `throw-down`. One event listener is definite faster than multiple. No question. There is certainly a reason react is doing it that way.

Cant we just use a single top-level addEventListener, if the event.target or parents have an onclick, fire that event? I guess we would need to cache and link a bunch of things.

I'll note, I have tried mounting around 5-10 thousand components on the same page using yoyo. All components had an onclick event listener. The Ram/CPU usage was minimal 60kb ram/0 idle CPU. So maybe the browser is built for this sort of thing (i.e. adding 10k event listeners).

**Comment by shama** [comment]
> Cant we just use a single top-level addEventListener, if the event.target or parents have an onclick, fire that event? I guess we would need to cache and link a bunch of things.

If I have an app with `button-component@1.0.0` using `yo-yo@1.0.0` and `table-component@1.0.0` using `yo-yo@2.0.0`, we don't know which version of `yo-yo` should win as the single top level addEventListener.

React can do it because all React components have a peer dependency to React. So each time React updates, they expect everyone to update their components or risk becoming incompatible. This is the primary thing I would like to avoid happening to `yo-yo`. If we avoid peer dependencies, we can create as many components as we want without fearing them becoming incompatible due to framework updates.

**Comment by SilentCicero** [comment]
@shama okay, great point. Yeah in that case I'm not sure.

**Comment by yoshuawuyts** [comment]
> The Ram/CPU usage was minimal 60kb ram/0 idle CPU. So maybe the browser is built for this sort of thing (i.e. adding 10k event listeners)

Hah, if it's not posing perf problems then I don't see why it should be added. One particular field where I've found global handling of events to be useful is [for handling href links](https://github.com/yoshuawuyts/sheet-router/blob/master/href.js) on an application level. Perhaps creating a global handler for other events could work on application level too? - tho that's more of an experiment, agree it shouldn't be part of `yo-yo`

**Comment by markbrown4** [comment]
There's certainly merit to doing event delegation well but you do need good examples to test how much benefit it really has.  I haven't compared in years but older IE's used to crawl to a halt when too many event listeners were registered.  It prevents the need for re-registering on updates too.

I have no idea of the yo-yo internals but if it's possible to fire the events with a yo-yo version attached then it should be possible to coordinate things at the top across how ever many events are registered.

Still, as long as all of the events bubble up then it's possible for people to implement it on their own _when_ it's a problem.

``` js
var yo = require('yo-yo')
var manyTimes = [];
for (var i = 1; i <= 100; i++) {
  manyTimes.push(i);
}
var clicker = (event)=> {
  // TODO walk up the DOM, match selector / nodeName, do we care about this event?
  var li = event.target;
  alert(li.innerHTML)
}
var list = yo`
<ul style="height: 100%; overflow: auto" onclick=${clicker}>
  ${manyTimes.map((item)=> yo`<li>${item}</li>` )}
</ul>
`
document.body.appendChild(list)
```

A nice to have that could have big perf benefits.

**Comment by bendrucker** [comment]
shama and I talked about this a bit and came to a similar conclusion to your example @markbrown4. I feel like a cost of writing isolated components is that developers need to be capable of understanding and implementing a simple event delegation pattern. It'd be cool to reference a helper module for people who need it. I don't see a way to do sane global delegation without bringing back the peer dep problem.
