### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by ghost** [maxogden/yo-yo#26]
Does yo-yo support SVG?
Thank you.

**Comment by yoshuawuyts** [comment]
@pmros yeah, it should! Anything in particular you're running into?

**Comment by ghost** [comment]
Not yet. I'll try later. Thank you.

**Comment by nichoth** [comment]
Yes it is comfirmed by me to support svg. Although there may be some hyperx
issues with self closing tags, which is ok, it just means you have to patch
hyperx for tag names. like in #23
