### ISSUE TITLE
type attribute doubling on <input>

### ISSUE THREAD

**Issue by seangenabe** [maxogden/yo-yo#33]
Running

``` javascript
(yo`<input type="checkbox">`).toString()
```

yields

``` javascript
'<input type="text" type="checkbox" />'
```

Using yo-yo v1.2.2.

**Comment by shama** [comment]
@seangenabe Is that when ran on the server side?

**Comment by seangenabe** [comment]
Yes.

**Comment by ghost** [comment]
I am using choo and I had same issue. I had to update min-document module to latest version (2.19.0). Check out comments @ https://github.com/Raynos/min-document/pull/41 
Maybe this is related?

**Comment by yoshuawuyts** [comment]
seems like `rm -rf node_modules && npm install` should resolve this; semver should bump `min-document` in the tree

**Comment by shama** [comment]
Closing as this is now fixed.
