### ISSUE TITLE
PSA: morphdom v2 released

### ISSUE THREAD

**Issue by patrick-steele-idem** [maxogden/yo-yo#41]
FYI, I just published `morphdom@2` with some improvements:

---
- Fixed [#47](https://github.com/patrick-steele-idem/morphdom/issues/47) - Detect and handle reorder of siblings
- `onNodeAdded` is now called for all on child nodes and not just the root node (closes [PR #57](https://github.com/patrick-steele-idem/morphdom/pull/57))
- Simplified code and reduced overall code size
- NOTE: Performance is about the same or slightly better than the previous version of `morphdom` based on benchmarks
- Added examples:[./examples/](https://github.com/patrick-steele-idem/morphdom/tree/master/examples)
#### Breaking changes
- `onNodeAdded` is now called for all on child nodes (not just the root node)
- Removed deprecated options:
  - `onBeforeMorphEl` (use `onBeforeElUpdated` instead)
  - `onBeforeMorphElChildren` (use `onBeforeElChildrenUpdated` instead)

---

See: [morphdom/CHANGELOG](https://github.com/patrick-steele-idem/morphdom/blob/master/CHANGELOG.md#200)

When you have a chance to upgrade please let me know if you see any issues.

Cheers.

**Comment by shannonmoeller** [comment]
You just made my day. Thanks for this!

**Comment by shama** [comment]
Thanks @patrick-steele-idem!

**Comment by timwis** [comment]
That's exciting news @patrick-steele-idem!

FYI, I tried out upgrading morphdom in yo-yo locally and it appears to have broken the following tests:
- [event attribute gets removed](https://github.com/maxogden/yo-yo/blob/master/test.js#L15) (expected 1, actual 2)
- [input values get copied](https://github.com/maxogden/yo-yo/blob/master/test.js#L46) (expected 'hi', actual '')

**Comment by patrick-steele-idem** [comment]
@timwis thanks for taking a look. The breaking test looks to be due to the following breaking change in `morphdom`:
- Removed options:
  - `onBeforeMorphEl` (use `onBeforeElUpdated` instead)
  - `onBeforeMorphElChildren` (use `onBeforeElChildrenUpdated` instead)

Fortunately, it should be a simple change to the following line:

https://github.com/maxogden/yo-yo/blob/656992c1553782c779c9de4c711614b16c7f342a/index.js#L11

Something like the following should work:

``` javascript
if (opts.onBeforeMorphEl) { // If you need to support the old `onBeforeMorphEl`
  opts.onBeforeElUpdated = opts.onBeforeMorphEl
}
if (!opts.onBeforeElUpdated) opts.onBeforeElUpdated = copier
```

**Comment by kristoferjoseph** [comment]
We should close this issue now that #51 has landed 😸

**Comment by shama** [comment]
Thanks @kristoferjoseph!
