### ISSUE TITLE
onload / onunload events 

### ISSUE THREAD

**Issue by kristoferjoseph** [maxogden/yo-yo#47]
@shama How do you need to write yo-yo components to take advantage of bel's onload / unload behavior?

**Comment by yoshuawuyts** [comment]
We're waiting for a new `morphdom` release to add support for this; I created a lil playground to show off how to create stateful components with `morphdom` :sparkles: - we should probably create a nice lil wrapper that can memoize based on arguments at some point, but hope the repo can provide some help for now - cheers! :v:

### See Also
- https://github.com/patrick-steele-idem/morphdom/pull/81
- https://github.com/shama/on-load/issues/10
- https://github.com/patrick-steele-idem/morphdom/issues/77

**Comment by kristoferjoseph** [comment]
Nice! I'm down to write a wrapper. Did you link to the playground you wrote?

**Comment by yoshuawuyts** [comment]
oooops https://github.com/yoshuawuyts/playground-stateful-choo/blob/master/index.js :D

**Comment by kristoferjoseph** [comment]
Did some more experiments and `load`/`unload` work currently, but not for cached elements, that was my issue. I see now why you jumped directly to that comment @yoshuawuyts. 
Was looking at how [diablo](https://github.com/chromakode/diablo) is adding more lifecycle events. Would be nice for adding `css` intro and exit transitions.

**Comment by yoshuawuyts** [comment]
@kristoferjoseph I think extra lifecycle events can be evaded by using a finite state machine; `onload` / `onunload` should be the only hooks needed at the component level to create css animations. Perhaps take a look at [the f1 package](https://www.npmjs.com/package/f1) for an example of an animation state machine
