### ISSUE TITLE
Problems with textarea

### ISSUE THREAD

**Issue by emanchado** [maxogden/yo-yo#52]
It seems that there's a bug with keeping the value of textareas. A solution for it is described here:

https://github.com/patrick-steele-idem/morphdom/issues/88#issuecomment-252784028

You have a bit more context information at https://github.com/yoshuawuyts/choo/issues/253 (which is already linked from the first URL).

**Comment by shama** [comment]
Related issue: https://github.com/shama/bel/issues/36

**Comment by phated** [comment]
@shama do you see a problem with the following solution?

> There's a line in yo-yo https://github.com/maxogden/yo-yo/blob/master/index.js#L31
> 
> If you flip the t/f you ge the expected outcome: https://esnextb.in/?gist=81944ffdfa6ebc00827d58d7c5a91441
> 
> I'm unable to reproduce this in morphdom under several variations of generating the html described.
> 
> I'm going to close this.

**Comment by phated** [comment]
Thanks @shama!

**Comment by tors** [comment]
Thank you @shama!
