### ISSUE TITLE
select element not registering event handlers?

### ISSUE THREAD

**Issue by bfulop** [maxogden/yo-yo#72]
No matter how hard I try, I can only register event handlers for the `onmouseover` event with the `<select>` element. The other event types disappear once the element is rendered. 

```js
var html = require('yo-yo')

var logger = e => console.log(e)

html`
<select id="myselect" oninput="${logger}" onmouseover=${logger}>
     <option value="mono">Mono</otion>
     <option value="serif">Serif</otion>
</select>
`
```

Any ideas why this could be and how to get around this issue? (Other than adding the event listeners externally?)

**Comment by shama** [comment]
The attribute `oninput="${logger}"` should be unquoted: `oninput=${logger}`.

**Comment by bfulop** [comment]
😅
 
Sorry it's just one those times when you should just take break instead of mindlessly hitting the keyboard...

Thanks for the quick reply, saved my day!
